config/routes.rb
Rails.application.routes.draw do
	# 顧客用
	# URL /customers/sign_in ...
	devise_for :customers, skip: [:passwords], controllers: {
		registrations: "public/registrations",
		sessions: 'public/sessions'
	}

	scope module: 'public' do
		get '/customers/my_page', to: 'customers#my_page', as: 'customers_my_page' #マイページ用のルート
		get '/customers/information/edit', to: 'customers#edit', as: 'customers_information_edit'
		resources :customers, only: [:update] do # 顧客リソース用のルートを追加
		  get :confirm, on: :member # 退会確認ページ用のルート
      patch :withdrawal, on: :member # 退会処理用のルート
		end
		resources :items, only: [:index, :show] #顧客用のitemsルート
		resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    post '/orders/confirmation', to: 'orders#confirmation', as: 'orders_confirmation' #注文情報確認ページルート
  	get '/orders/complete', to: 'orders#complete', as: 'orders_complete' #注文情報確認ページルート
    resources :orders, only: [:new, :create, :index, :show]
	end

	namespace :admin do
		resources :items,only: [:index, :new, :create, :show, :edit, :update, :destroy] # 管理者用の items ルート
	  resources :customers,only: [:index, :show, :edit, :update] # 管理者用の customers ルート
    resources :orders,only: [:show, :index]
    resources :orders_detail,only: [:show]
	end

	# 管理者用
	# URL /admin/sign_in ...
	devise_for :admin, skip: [:registrations, :passwords], controllers: {
		sessions: "admin/sessions"
	}

	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root to: "homes#top"
	get '/about', to: 'homes#about', as: 'home_about' #aboutページルート
  get '/items', to: 'public/items#index', as: 'item_index' #商品一覧ページルート

  get '/items/:id', to: 'public/items#show', as: 'item_show' #商品ページルート
  get '/cart_items', to: 'public/cart_items#index', as: 'cart_items_index' #カートページルート
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders


  def activate!
    update(is_active: true)
  end

  def deactivate!
    update(is_active: false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all # 有効な顧客と退会した顧客をすべて取得
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update #顧客の登録情報更新
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = '登録情報を更新しました'
      redirect_to admin_customers_path(@customer) # 更新成功時にマイページにリダイレクト
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h5><span style="background-color: #dcdcdc;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span></h5>
  
  <div class="row">
    <div class="col-md-8">
    
    <%= form_for @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
    
      <!-- エラーチェック -->
      <% if @customer.errors.any? %>
        <%= @customer.errors.count %> errors prohibited this obj from being saved:
        <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      
      <div>会員ID <%= @customer.id %></div>
    
      <div class="field">
        <%= f.label :氏名 %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
      </div>
    
      <div class="field">
        <%= f.label :フリガナ %>
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
      </div>
    
      <div class="field">
        <%= f.label :postal_code, "郵便番号" %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
      </div>
    
      <div class="field">
        <%= f.label :住所 %>
        <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
      </div>
    
      <div class="field">
        <%= f.label :telephone_number, "電話番号" %>
        <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
      </div>
    
      <div class="field">
        <%= f.label :メールアドレス %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
    
      <div class="form-group">
        <%= f.label :is_active, "会員ステータス" %><br>
        <label class="btn btn <%= 'active' if @customer.is_active? %>" <%= @customer.is_active? ? 'black' : 'transparent' %>">
          <%= f.radio_button :is_active, true, class: 'form-check-input' %> 有効
        </label>
        <label class="btn btn <%= 'active' unless @customer.is_active? %>" <%= @customer.is_active? ? 'transparent' : 'black' %>">
          <%= f.radio_button :is_active, false, class: 'form-check-input' %> 退会
        </label>
      </div>
    </div>
  </div>  
    
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= f.submit "変更を保存" ,class: "btn btn-success" %>
    </div>
  </div>
  
    <% end %>
    
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h5><span style="background-color: #dcdcdc;">会員一覧</span></h5>
  <div class="row justify-content-center">

    <div class="col-8">

    <table class = "table table-striped">

      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name , admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active? %>
                <span class='active-status'>有効</span>
              <% else %>
                <span class='inactive-status'>退会</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>

    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h5><span style="background-color: #dcdcdc;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h5>

  <div class="row">
    <div class="col-md-8">

    <table class = "table">
      <tbody>
        <% if @customer.present? %>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
       　  <tr>
            <th>カナ</th>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
           <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %>
          </tr>
           <tr>
            <th>住所</th>
            <td><%= @customer.address %>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td><%= @customer.is_active ? "有効" : "退会" %>
          </tr>

        <% end %>
      </tbody>
    </table>

    <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>

   </div>
  </div>
</div>