config/routes.rb
Rails.application.routes.draw do
	# 顧客用
	# URL /customers/sign_in ...
	devise_for :customers, skip: [:passwords], controllers: {
		registrations: "public/registrations",
		sessions: 'public/sessions'
	}

	scope module: 'public' do
		get '/customers/my_page', to: 'customers#my_page', as: 'customers_my_page' #マイページ用のルート
		get '/customers/information/edit', to: 'customers#edit', as: 'customers_information_edit'
		resources :customers, only: [:update] do # 顧客リソース用のルートを追加
		  get :confirm, on: :member # 退会確認ページ用のルート
      patch :withdrawal, on: :member # 退会処理用のルート
		end
		resources :items, only: [:index, :show] #顧客用のitemsルート
		resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    post '/orders/confirmation', to: 'orders#confirmation', as: 'orders_confirmation' #注文情報確認ページルート
  	get '/orders/complete', to: 'orders#complete', as: 'orders_complete' #注文情報確認ページルート
    resources :orders, only: [:new, :create, :index, :show]
	end

	namespace :admin do
		resources :items,only: [:index, :new, :create, :show, :edit, :update, :destroy] # 管理者用の items ルート
	  resources :customers,only: [:index, :show, :edit, :update] # 管理者用の customers ルート
    resources :orders,only: [:show, :index]
    resources :orders_detail,only: [:show]
	end

	# 管理者用
	# URL /admin/sign_in ...
	devise_for :admin, skip: [:registrations, :passwords], controllers: {
		sessions: "admin/sessions"
	}

	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root to: "homes#top"
	get '/about', to: 'homes#about', as: 'home_about' #aboutページルート
  get '/items', to: 'public/items#index', as: 'item_index' #商品一覧ページルート

  get '/items/:id', to: 'public/items#show', as: 'item_show' #商品ページルート
  get '/cart_items', to: 'public/cart_items#index', as: 'cart_items_index' #カートページルート
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders


  def activate!
    update(is_active: true)
  end

  def deactivate!
    update(is_active: false)
  end

end

app/models/ganre.rb
class Ganre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_one_attached :image
  has_many :cart_items
  has_many :order_details

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  # 画像のサイズを100x100ピクセルに変更するメソッド
  def resize_image
    if image.attached?
      image.variant(resize: '100x100')
    else
      # デフォルトの画像を表示する場合の処理
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      return File.open(file_path)
    end
  end

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details

  #注文内のすべての注文詳細の小計を合計して合計金額を計算
  def calculate_total_payment
    total_payment = 0
    self.order_details.each do |order_detail|
      total_payment += order_detail.calculate_subtotal
    end
    total_payment
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  #注文詳細ごとの小計（subtotal）を計算
  def calculate_subtotal
    self.amount * self.purchase_price
  end
end

app/models/orders_detail.rb
class OrdersDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index # データの一覧を表示する
    @item = Item.new
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create #データを追加（保存）する
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] ='Item was successfully created.'
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show #データの内容（詳細）を表示する
    @item = Item.find(params[:id])
  end

  def edit #データを更新するためのフォームを表示す
    @item = Item.find(params[:id])
  end

  def update #データを更新する
   @item = Item.find(params[:id])
    if @item.update(item_params)
     #flash[:notice] ='You have updated book successfully.'
     redirect_to admin_item_path(@item.id)
    else
     render :edit
    end
  end

  def destroy #データを削除する
    @item = Item.find(params[:id])  # データ（レコード）を1件取得
    @item.destroy  # データ（レコード）を削除
    #flash[:notice] ='Book was successfully destroyed.'
    #redirect_to items_path # 投稿一覧画面へリダイレクト
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index # 注文一覧を表示する
    @orders = Order.page(params[:page])
  end

  def show #注文履歴を表示する
    @order = Order.find(params[:id]) #注文IDから注文を取得
    @order_details = @order.order_details.all # 注文に関連する商品情報を取得
    @total_payment = @order.calculate_total_payment # 合計金額を計算
  end

  def update # データを更新する
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order)
    else
      render :edit
    end
  end

  def destroy # データを削除する
    @order = Order.find(params[:id]) # 注文を取得
    @order.destroy # 注文を削除
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :shipping_postal_code, :shipping_address, :shipping_name, :postage, :total_payment, :payment_method)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @new_items = Item.order(created_at: :desc).limit(4) # 例: 最新の4個のアイテムを取得
  end
  
  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_detail_helper.rb
module Admin::OrdersDetailHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1a020bd911.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg text-black">
        <div class="container">
          <div class="navbar-brand" href="/">
            <%= link_to "NaganoCafe", root_path, style: "font-size: 2rem;" %>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <!-- 共通のメニュー項目（誰もログインしていない状態） -->

              <% if customer_signed_in? %><!-- 顧客がログインしている場合のメニュー項目 -->
                <li class="nav-item">
                  <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "商品一覧", item_index_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>

              <% elsif admin_signed_in? %><!-- 管理者がログインしている場合のメニュー項目 -->

                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>


              <% else %>
                <li class="nav-item">
                <%= link_to "About", home_about_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "商品一覧", item_index_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
                </li>
               <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= flash[:success] %>
    <%= flash[:error] %>
    <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>